### ISSUE TITLE
Mot de passe en variable

### ISSUE THREAD

**Issue by Safranil** [tomitomas/DigiAction#17]
Bonjour,

Est-il possible d'ajouter la possibilité d'utiliser une variable ou une commande pour changer dynamiquement les codes utilisés par le plugin.

Cela permettrait de créer un code journalier pour désactiver une alarme par un tiers sans qu'il ne soit connu définitivement par le tiers.

Merci d'avance.

**Comment by tomitomas** [comment]
Salut @Safranil, 

peux tu créer tes 2 sujets sur community svp ? 
je n'avais pas vu que j'avais laissé ouvert la partie "issue", je vais donc le désactiver car je n'ai pas envie de devoir gérer les demandes à plusieurs endroits :)

merci

**Comment by tomitomas** [comment]
non pas intéressé @Safranil ? :(

ca permettrait en plus à d'autres personnes de donner leur avis ! 
j'ai déjà initié qlq chose ...

**Comment by Safranil** [comment]
Bonjour @tomitomas, j'ai été indisponible la semaine précédente. J'ai créé les deux sujets sur la communauté :

https://community.jeedom.com/t/digiaction-lancer-une-commande-scenario-en-cas-de-code-faux/65752
https://community.jeedom.com/t/digiaction-mot-de-passe-en-variable/65749

**Comment by tomitomas** [comment]
fix in 5fe244c
